---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python

python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Check bash version
  - bash --version
  # Install ansible
  - pip install ansible; ansible --version

# Run
script:
  # Basic role syntax check
  - ansible-playbook ansible-user.yml --syntax-check
  # Syntax check
  - bash -n ansible-user.sh
  # Create an authorized keys
  - bash ansible-user.sh init
  # Create a user
  - export ANSIBLE_USER_DEBUGRUN=yes && bash ansible-user.sh create -h localhost --local

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
#  email:
#  - youremailaddress

